"""Added the pitches model class

Revision ID: 72f59c0aebaa
Revises: 
Create Date: 2022-03-10 15:29:57.069059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f59c0aebaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_txt', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('upvt', sa.String(), nullable=True),
    sa.Column('dwnvt', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('pitch_category', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitches')
    # ### end Alembic commands ###
